apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: secret-default
  namespace: test
  annotations:
    kubernetes.io/service-account.name: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: secret-developer
  namespace: test
  annotations:
    kubernetes.io/service-account.name: developer

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: secret-sysop
  namespace: test
  annotations:
    kubernetes.io/service-account.name: sysop
